spring:
  application:
    name: api-gateway

# Logging
logging:
  level:
    "[org.springframework.security]": INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, threaddump
  endpoint:
    health:
      show-details: always
